/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122467-gc3d3377fe1-20260117"
#endif /* AVUTIL_FFVERSION_H */
